name: "Build"
on: { push: { branches: [ "main" ] } }
jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: cachix/cachix-action@v14
      with:
        name: cp437-tools
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        nix -L build github:srid/devour-flake \
          --no-link --print-out-paths \
          --override-input flake .
  cargo-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - run: |
        nix develop --command \
          cargo fmt --check
    - run: |
        nix develop --command \
          cargo clippy
    - run: |
        nix develop --command \
          cargo build --all-targets
    # TODO fix (stdout function returns errno 2)
    # - run: |
    #     nix develop --command \
    #       cargo test
