.TH cp437-to-png 1
." -----------------------------------------------------------------------------
.SH NAME
.B cp437-to-png
- Render a file as a PNG.
." -----------------------------------------------------------------------------
.SH SYNOPSIS
.B cp437-to-png
.I FILE
." -----------------------------------------------------------------------------
.SH DESCRIPTION
.B cp437-to-png
renders the given file as a PNG image, piping the resulting file to stdout.
.PP
It will also embed the file's metadata, if available.
." -----------------------------------------------------------------------------
.SH ARGUMENTS
.I FILE
.RS .5i
The file to be rendered.
.RE
