.TH cp437-thumbnail 1
." -----------------------------------------------------------------------------
.SH NAME
.B cp437-thumbnail
- Render a file as a thumbnail.
." -----------------------------------------------------------------------------
.SH SYNOPSIS
.B cp437-thumbnail
.I INPUT OUTPUT SIZE
." -----------------------------------------------------------------------------
.SH DESCRIPTION
.B cp437-thumbnail
renders the given file as a small PNG image. For use as a thumbnailer.
.PP
It will not embed the file's metadata.
." -----------------------------------------------------------------------------
.SH ARGUMENTS
.I INPUT
.RS .5i
The file to be rendered.
.RE
." -------------------------------------
.PP
.I OUTPUT
.RS .5i
The thumbnail output path.
.RE
." -------------------------------------
.PP
.I SIZE
.RS .5i
The max size of the thumbnail.
.RE
