.TH cp437-read-meta 1
." -----------------------------------------------------------------------------
.SH NAME
.B cp437-read-meta
- Read a file's metadata.
." -----------------------------------------------------------------------------
.SH SYNOPSIS
.B cp437-read-meta
.I FILE
." -----------------------------------------------------------------------------
.SH DESCRIPTION
.B cp437-read-meta
reads and prints a file's metadata, highlighting values to show potential
errors, as well as showing the effective value when a real one is missing.
." -----------------------------------------------------------------------------
.SH ARGUMENTS
.I FILE
.RS .5i
File's meta to be read.
.RE
