.TH cp437-check-meta 1
." -----------------------------------------------------------------------------
.SH NAME
.B cp437-check-meta
- Check a file's metadata.
." -----------------------------------------------------------------------------
.SH SYNOPSIS
.B cp437-check-meta
.I FILE
." -----------------------------------------------------------------------------
.SH DESCRIPTION
.B cp437-check-meta
reads a file's metadata and run some validations to see if there's any issues
with it.
." -----------------------------------------------------------------------------
.SH ARGUMENTS
.I FILE
.RS .5i
File to be checked.
.RE
