.TH cp437-help 1
." -----------------------------------------------------------------------------
.SH NAME
.B cp437-help
- Show a command's help text and exit.
." -----------------------------------------------------------------------------
.SH SYNOPSIS
.B cp437-help
.I COMMAND
." -----------------------------------------------------------------------------
.SH DESCRIPTION
.B cp437-help
grabs a simplified verison of a file's man page and prints it.
." -----------------------------------------------------------------------------
.SH ARGUMENTS
.I COMMAND
.RS .5i
Command's help to be queried.
.RE
