.TH cp437-to-svg 1
." -----------------------------------------------------------------------------
.SH NOTE
.B This binary is still a WIP. Redering seems to be kinda wonky.
." -----------------------------------------------------------------------------
.SH NAME
.B cp437-to-svg
- Render a file as an SVG.
." -----------------------------------------------------------------------------
.SH SYNOPSIS
.B cp437-to-svg
.I FILE
." -----------------------------------------------------------------------------
.SH DESCRIPTION
.B cp437-to-svg
renders the given file as an SVG image, piping the resulting file to stdout.
.PP
It will also embed the file's metadata, if available.
." -----------------------------------------------------------------------------
.SH ARGUMENTS
.I FILE
.RS .5i
The file to be rendered.
.RE
